gshell cd --with-id 1cNm3uCaWlfCjIXWOPUF8P7E7nLrJ08N5
gshell download dataset_cosum_processed.h5
gshell download dataset_ovp_processed.h5
gshell download dataset_summe_processed.h5
gshell download dataset_tvsum_processed.h5
gshell download dataset_youtube_processed.h5
gshell download eccv16_dataset_ovp_google_pool5.h5
gshell download eccv16_dataset_summe_google_pool5.h5
gshell download eccv16_dataset_tvsum_google_pool5.h5
gshell download eccv16_dataset_youtube_google_pool5.h5